#!/usr/bin/env bash

# Exit if any subcommand fails
set -e
set -o pipefail

source script/helpers/text_helpers


notice "Running System Check"
./script/system_check
print_done

notice "Creating the database"
./tasks db.create | indent

notice "Verifying postgres connection"
./tasks db.verify_connection | indent

notice "Migrating the database"
./tasks db.migrate | indent

notice "Seeding the database with required and sample records"
./tasks db.seed.required_data | indent
./tasks db.seed.sample_data | indent

print_done
